# Goal (true if new goal received)
bool target_pose
---
# Result (true if goal reached, false if aborted)
bool success
---
# Feedback (true if server is processing goal and not preempted)
# (false if preempted)
bool current_pose
